# version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./users.yaml:/home/app/web/users.yaml
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
      - pages_volume:/home/app/web/project/pages
      - templates_volume:/home/app/web/project/templates
      - /tmp/fodexchange:/mnt/exchange
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    volumes:
      - ./services/db/postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:latest
    #ports:
    #  - 6379:6379
    volumes:
      - redis_data:/data
      # - tmp_volume:/tmp

  nginx:
    build: ./services/nginx
    volumes:
      - ./certificates:/etc/nginx/ssl
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
      - pages_volume:/home/app/web/project/pages
      - templates_volume:/home/app/web/project/templates
    ports:
      # - 1337:80
      # - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
  pages_volume:
  templates_volume:
  redis_data:
  # tmp_volume:
