###########
# BUILDER #
###########

# pull official base image
FROM python:3.11-slim-bookworm AS builder

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc && \
    rm -rf /var/lib/apt/lists/*

# install python dependencies first for optimal Docker layer caching
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt

COPY . /usr/src/app/


#########
# FINAL #
#########

# pull official base image
FROM python:3.11-slim-bookworm

# create directory for the app user
RUN mkdir -p /home/app

# create the app user with home /home/app
RUN addgroup --system app && adduser --system --group --home /home/app app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends netcat-traditional gosu && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

# copy entrypoint-prod.sh
COPY ./entrypoint.prod.sh $APP_HOME

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R app:app /home/app

# run entrypoint.prod.sh (handles permissions and privilege drop to app user)
ENTRYPOINT ["/home/app/web/entrypoint.prod.sh"]
